version: '3'

networks:
     laravel:

services:
    nginx:
        image: nginx:stable-alpine
        container_name: nginx
        depends_on:
            - php
            - mysql
        networks:
            - laravel:

    mysql:
        networks:
            - laravel:

    php:
        networks:
            - laravel:
