version: '3'

networks:
     laravel:

services:
    nginx:
        image: nginx:stable-alpine
        container_name: nginx
        ports:
            - "8080:80"
        volumes:
            - ./src:/var/www/html
        depends_on:
            - php
            - mysql
        networks:
            - laravel:

    mysql:
        networks:
            - laravel:

    php:
        networks:
            - laravel:
